
import { Accommodation, AccommodationType, TransferType, MealPlan, Offer, Experience, BlogPost } from './types';

export const RESORTS: Accommodation[] = [
  // --- ULTRA LUXURY & SIGNATURE ---
  {
    id: 'soneva-jani',
    name: 'Soneva Jani',
    slug: 'soneva-jani-luxury-overwater-villas',
    type: AccommodationType.RESORT,
    atoll: 'Noonu Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Iconic overwater villas with private slides into the lagoon.',
    description: 'Soneva Jani is a sanctuary of sustainable luxury. Each villa opens to its own stretch of lagoon and comes with a private pool and a retractable roof to stargaze from the master bedroom.',
    images: ['https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&q=80&w=1200'],
    features: ['Retractable Roof', 'Water Slides', 'Private Pools', 'Outdoor Cinema'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.HALF_BOARD, MealPlan.ALL_INCLUSIVE],
    uvp: 'The only resort in the Maldives with retractable roofs for stargazing and private slides in every villa.',
    isFeatured: true
  },
  {
    id: 'one-only-reethi-rah',
    name: 'One&Only Reethi Rah',
    slug: 'one-and-only-reethi-rah-maldives-luxury',
    type: AccommodationType.RESORT,
    atoll: 'North Male Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Ultra-luxury private island with twelve pristine beaches.',
    description: 'One&Only Reethi Rah offers an unrivaled level of style and sophistication. Surrounded by the crystal clear waters of the Indian Ocean, this superb all-villa resort offers a sanctuary of privacy.',
    images: ['https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&q=80&w=1200'],
    features: ['12 Pristine Beaches', 'Beach Club', 'Private Concierge', 'Overwater Yoga'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Celebrity-favorite private island with twelve distinct beaches and world-class luxury.',
    isFeatured: true
  },
  {
    id: 'conrad-rangali',
    name: 'Conrad Maldives Rangali Island',
    slug: 'conrad-maldives-rangali-island-underwater-villa',
    type: AccommodationType.RESORT,
    atoll: 'South Ari Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Home to the world\'s first underwater villa, The MURAKA.',
    description: 'A pioneer of luxury, Conrad Rangali is set across two islands connected by a bridge, offering the Maldives\' first underwater dining and the first underwater villa.',
    images: ['https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?auto=format&fit=crop&q=80&w=1200'],
    features: ['Underwater Dining', 'The MURAKA Villa', 'Overwater Spa', 'Whale Shark Excursions'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD, MealPlan.FULL_BOARD],
    uvp: 'Experience the world\'s first underwater residence and world-renowned underwater dining at Ithaa.',
    isFeatured: true
  },
  {
    id: 'four-seasons-landaa',
    name: 'Four Seasons Resort Maldives at Landaa Giraavaru',
    slug: 'four-seasons-landaa-giraavaru-baa-atoll',
    type: AccommodationType.RESORT,
    atoll: 'Baa Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'UNESCO Biosphere sanctuary with world-class marine conservation.',
    description: 'Four Seasons Landaa Giraavaru combines innovation, conservation, and luxury in equal measure within the Baa Atoll UNESCO World Biosphere Reserve.',
    images: ['https://images.unsplash.com/photo-1573843225233-9fca73af994d?auto=format&fit=crop&q=80&w=1200'],
    features: ['Manta Ray Conservation', 'Marine Discovery Centre', 'Ayurvedic Wellness', 'Jungle Estates'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Pioneering marine research and conservation programs in a UNESCO World Biosphere Reserve.'
  },
  {
    id: 'adaaran-vadoo',
    name: 'Adaaran Prestige Vadoo',
    slug: 'adaaran-prestige-vadoo-luxury',
    type: AccommodationType.RESORT,
    atoll: 'South Male Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'Exclusive adults-only villas with private plunge pools.',
    description: 'The gateway to the South Male Atoll, Vadoo offers a boutique experience where every villa is overwater and features a glass-bottom bathroom floor.',
    images: ['https://images.unsplash.com/photo-1510011564758-29df30730163?auto=format&fit=crop&q=80&w=1200'],
    features: ['Adults Only', 'Butler Service', 'Glass Floors', 'Sunset Views'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.ALL_INCLUSIVE],
    uvp: 'Intimate, adults-only luxury with award-winning villas and personalized butler service.'
  },
  {
    id: 'alila-kothaifaru',
    name: 'Alila Kothaifaru Maldives',
    slug: 'alila-kothaifaru-maldives-luxury',
    type: AccommodationType.RESORT,
    atoll: 'Raa Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'Minimalist architecture in the pristine Raa Atoll.',
    description: 'Designed by STUDIOGOTO, Alila Kothaifaru offers a seamless blend of contemporary architecture and the natural landscape of the Maldives.',
    images: ['https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?auto=format&fit=crop&q=80&w=1200'],
    features: ['Modernist Villas', 'Infinity Pools', 'Marine Discovery', 'Spa Alila'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'A masterpiece of contemporary design in an untouched tropical paradise.'
  },
  {
    id: 'amilla-maldives',
    name: 'Amilla Maldives',
    slug: 'amilla-maldives-resort',
    type: AccommodationType.RESORT,
    atoll: 'Baa Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'Spacious white villas and holistic wellness approach.',
    description: 'Known for its spacious white villas and "Wellness Your Way" philosophy, Amilla offers a modern, stylish take on island living.',
    images: ['https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&q=80&w=1200'],
    features: ['Glamping in a Bubble', 'Wellness Menus', 'House Reef', 'Tree Houses'],
    transfers: [TransferType.SEAPLANE, TransferType.DOMESTIC_FLIGHT],
    mealPlans: [MealPlan.HALF_BOARD, MealPlan.ALL_INCLUSIVE],
    uvp: 'One of the largest islands in Baa Atoll offering unusually spacious minimalist villas.'
  },
  {
    id: 'anantara-kihavah',
    name: 'Anantara Kihavah Maldives Villas',
    slug: 'anantara-kihavah-maldives-villas',
    type: AccommodationType.RESORT,
    atoll: 'Baa Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Overwater observatory and underwater dining.',
    description: 'Located on Kihavah Huravalhi, this resort is home to the Maldives\' only overwater observatory and a multi-award-winning underwater restaurant.',
    images: ['https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&q=80&w=1200'],
    features: ['SKY Observatory', 'SEA Underwater Restaurant', 'Private Pools', 'Manta Excursions'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Dine 5 meters below the sea or stargaze from the only overwater observatory in the Maldives.'
  },
  {
    id: 'ayada-maldives',
    name: 'Ayada Maldives',
    slug: 'ayada-maldives-luxury-resort',
    type: AccommodationType.RESORT,
    atoll: 'Gaafu Dhaalu Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'Turkish-inspired luxury in the pristine south.',
    description: 'Voted one of the best luxury resorts globally, Ayada offers Turkish hospitality and one of the largest spas in the region.',
    images: ['https://images.unsplash.com/photo-1502602898657-3e917247a183?auto=format&fit=crop&q=80&w=1200'],
    features: ['Turkish Hammam', 'Wine Cheese Cellar', 'Surfing Access', 'Kids Club'],
    transfers: [TransferType.DOMESTIC_FLIGHT, TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD, MealPlan.ALL_INCLUSIVE],
    uvp: 'Award-winning Turkish hospitality and a world-class surfing break on your doorstep.'
  },
  {
    id: 'baglioni-maldives',
    name: 'Baglioni Resort Maldives',
    slug: 'baglioni-resort-maldives-italian-luxury',
    type: AccommodationType.RESORT,
    atoll: 'Dhaalu Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'Italian grace and style in a tropical setting.',
    description: 'Baglioni Resort Maldives brings Italian luxury to the heart of the Maldives, offering fine dining and an elegant lifestyle.',
    images: ['https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&q=80&w=1200'],
    features: ['Italian Fine Dining', 'Ferrari Trento Bar', 'Yoga Pavilion', 'PADI Dive Centre'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD, MealPlan.ALL_INCLUSIVE],
    uvp: 'The ultimate blend of Italian style and Maldivian serenity.'
  },
  {
    id: 'baros-maldives',
    name: 'Baros Maldives',
    slug: 'baros-maldives-legendary-resort',
    type: AccommodationType.RESORT,
    atoll: 'North Male Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'The legendary romantic sanctuary of the Maldives.',
    description: 'An iconic boutique resort, Baros has been setting the standard for Maldivian luxury for decades with its incredible house reef and overwater dining.',
    images: ['https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&q=80&w=1200'],
    features: ['Lighthouse Restaurant', 'Piano Deck Dining', 'Marine Centre', 'Private Island Picnics'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Consistently voted the world\'s most romantic resort and home to an unparalleled house reef.'
  },
  {
    id: 'como-cocoa-island',
    name: 'COMO Cocoa Island',
    slug: 'como-cocoa-island-wellness',
    type: AccommodationType.RESORT,
    atoll: 'South Male Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'Minimalist luxury with iconic dhoni-shaped villas.',
    description: 'COMO Cocoa Island is an intimate private island resort with 33 overwater suites, designed for privacy and wellness.',
    images: ['https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?auto=format&fit=crop&q=80&w=1200'],
    features: ['COMO Shambhala Wellness', 'Dhoni Villas', 'Diving & Snorkeling', 'Organic Cuisine'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Iconic dhoni-shaped overwater villas and the world-renowned COMO Shambhala wellness center.'
  },
  {
    id: 'joali-maldives',
    name: 'JOALI Maldives',
    slug: 'joali-maldives-art-resort',
    type: AccommodationType.RESORT,
    atoll: 'Raa Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'The first art-immersive luxury resort in the Maldives.',
    description: 'JOALI is a sophisticated retreat where art meets island life. Each villa is a masterpiece of design and craftsmanship.',
    images: ['https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&q=80&w=1200'],
    features: ['Art Installations', 'Whiskey & Cigar Lounge', 'Flower Garden', 'Marine Discovery'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'A curated journey of artistic discovery and emotional luxury in the Raa Atoll.'
  },
  {
    id: 'kandima-maldives',
    name: 'Kandima Maldives',
    slug: 'kandima-maldives-lifestyle-resort',
    type: AccommodationType.RESORT,
    atoll: 'Dhaalu Atoll',
    priceRange: '$$',
    rating: 4,
    shortDescription: 'Vibrant, stylish and affordable lifestyle resort.',
    description: 'Kandima is more than just a holiday; it\'s a lifestyle destination with a cool, modern aesthetic and high-energy vibes.',
    images: ['https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&q=80&w=1200'],
    features: ['Art Studio', 'longest Pool in Maldives', 'Multiple Restaurants', 'Water Sports'],
    transfers: [TransferType.DOMESTIC_FLIGHT, TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD, MealPlan.ALL_INCLUSIVE],
    uvp: 'The Maldives\' coolest lifestyle resort featuring the longest pool in the country and a vibrant social scene.'
  },
  {
    id: 'kuramathi-maldives',
    name: 'Kuramathi Maldives',
    slug: 'kuramathi-maldives-island-resort',
    type: AccommodationType.RESORT,
    atoll: 'Rasdhoo Atoll',
    priceRange: '$$',
    rating: 4,
    shortDescription: 'Large island with diverse accommodation and dining.',
    description: 'Kuramathi offers an naturally Maldivian experience with something for everyone, from overwater villas to garden estates.',
    images: ['https://images.unsplash.com/photo-1510011564758-29df30730163?auto=format&fit=crop&q=80&w=1200'],
    features: ['Sandbank Sunsets', 'Eco Centre', 'Multiple Pools', 'Kidz Club'],
    transfers: [TransferType.SPEEDBOAT, TransferType.SEAPLANE],
    mealPlans: [MealPlan.FULL_BOARD, MealPlan.ALL_INCLUSIVE],
    uvp: 'One of the most naturally diverse islands in the Maldives with a spectacular 1km sandbank.'
  },
  {
    id: 'oaga-art-resort',
    name: 'Oaga Art Resort Maldives',
    slug: 'oaga-art-resort-maldives',
    type: AccommodationType.RESORT,
    atoll: 'North Male Atoll',
    priceRange: '$$$',
    rating: 4,
    shortDescription: 'Authentic local art and culture focused resort.',
    description: 'Oaga Art Resort is a local-owned sanctuary celebrating the art, history, and people of the Maldives.',
    images: ['https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&q=80&w=1200'],
    features: ['Local Art Classes', 'Dhivehi Dining', 'Interactive Murals', 'Music Lounge'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.ALL_INCLUSIVE],
    uvp: 'An island dedicated to Maldivian creativity, storytelling, and local heritage.'
  },
  {
    id: 'patina-maldives',
    name: 'Patina Maldives, Fari Islands',
    slug: 'patina-maldives-fari-islands',
    type: AccommodationType.RESORT,
    atoll: 'North Male Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Conscious luxury and vibrant social hub at Fari Islands.',
    description: 'Patina Maldives is a place of sanctuary and connection, designed by renowned architect Marcio Kogan.',
    images: ['https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&q=80&w=1200'],
    features: ['Fari Marina Access', 'James Turrell Pavilion', 'Sustainable Living', 'Plant-based Dining'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Modern minimalist luxury with access to the vibrant Fari Marina beach club and art installations.'
  },
  {
    id: 'riu-atoll',
    name: 'Riu Atoll',
    slug: 'riu-atoll-all-inclusive',
    type: AccommodationType.RESORT,
    atoll: 'Dhaalu Atoll',
    priceRange: '$$',
    rating: 4,
    shortDescription: '24-hour all-inclusive comfort for families and couples.',
    description: 'Riu Atoll offers a hassle-free all-inclusive experience on a beautiful private island connected to Riu Palace Maldivas.',
    images: ['https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?auto=format&fit=crop&q=80&w=1200'],
    features: ['24h All Inclusive', 'Direct Beach Access', 'Children\'s Pool', 'Live Music'],
    transfers: [TransferType.DOMESTIC_FLIGHT, TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.ALL_INCLUSIVE],
    uvp: 'Superior 24-hour all-inclusive service with a vibrant, international atmosphere.'
  },
  {
    id: 'st-regis-vommuli',
    name: 'The St. Regis Maldives Vommuli Resort',
    slug: 'st-regis-maldives-vommuli-resort',
    type: AccommodationType.RESORT,
    atoll: 'Dhaalu Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Signature butler service and iconic architecture.',
    description: 'Set on a private island, this resort features the signature St. Regis Butler Service and architecture inspired by marine life.',
    images: ['https://images.unsplash.com/photo-1510011564758-29df30730163?auto=format&fit=crop&q=80&w=1200'],
    features: ['Butler Service', 'Iridium Spa', 'Whale Shark Bar', 'Anti-Gravity Yoga'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Unrivaled personalized service and the iconic overwater Whale Shark bar.'
  },
  {
    id: 'w-maldives',
    name: 'W Maldives',
    slug: 'w-maldives-vibrant-luxury',
    type: AccommodationType.RESORT,
    atoll: 'North Ari Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'Playful, chic, and vibrant luxury on a heart-shaped island.',
    description: 'Escape to W Maldives, a private island luxury resort where the "Whatever/Whenever" service philosophy comes to life.',
    images: ['https://images.unsplash.com/photo-1502602898657-3e917247a183?auto=format&fit=crop&q=80&w=1200'],
    features: ['Underground Club', 'House Reef', 'Away Spa', 'Glow-in-the-dark Beach'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.ALL_INCLUSIVE],
    uvp: 'Vibrant, high-energy luxury with one of the best house reefs in the country.'
  },
  {
    id: 'waldorf-astoria-ithaafushi',
    name: 'Waldorf Astoria Maldives Ithaafushi',
    slug: 'waldorf-astoria-maldives-luxury',
    type: AccommodationType.RESORT,
    atoll: 'South Male Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Unmatched culinary diversity across three islands.',
    description: 'Spanning three islands in the South Male Atoll, this resort offers the ultimate in exclusivity and dining excellence.',
    images: ['https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?auto=format&fit=crop&q=80&w=1200'],
    features: ['11 Dining Venues', 'Private Island Residences', 'Aqua Wellness Centre', 'Kids Club'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'The most extensive dining collection in the Maldives featuring Michelin-starred partnerships.'
  },
  {
    id: 'barefoot-eco-hotel',
    name: 'The Barefoot Eco Hotel',
    slug: 'barefoot-eco-hotel-maldives',
    type: AccommodationType.GUEST_HOUSE,
    atoll: 'Haa Alifu Atoll',
    priceRange: '$',
    rating: 4,
    shortDescription: 'Sustainability meets authentic local island charm.',
    description: 'Located on the local island of Hanimaadhoo, The Barefoot Eco Hotel offers a responsible tourism experience with resort-level luxury.',
    images: ['https://images.unsplash.com/photo-1510011564758-29df30730163?auto=format&fit=crop&q=80&w=1200'],
    features: ['Marine Conservation', 'Private Beach', 'Local Village Tours', 'Bicycle Rentals'],
    transfers: [TransferType.DOMESTIC_FLIGHT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD, MealPlan.FULL_BOARD],
    uvp: 'The premier eco-conscious hotel in the Maldives, supporting local community development.'
  },
  {
    id: 'anantara-veli',
    name: 'Anantara Veli Maldives Resort',
    slug: 'anantara-veli-adults-only',
    type: AccommodationType.RESORT,
    atoll: 'South Male Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'Adults-only romantic getaway with overwater serenity.',
    description: 'Anantara Veli offers an idyllic adults-only hideaway, perfect for couples seeking tranquility and romance.',
    images: ['https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&q=80&w=1200'],
    features: ['Adults Only', 'Overwater Villas', 'Wellness Spa', 'Surfing Access'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'One of the few dedicated adults-only sanctuaries in the South Male Atoll.'
  },
  {
    id: 'hurawalhi-maldives',
    name: 'Hurawalhi Island Resort',
    slug: 'hurawalhi-maldives-underwater-restaurant',
    type: AccommodationType.RESORT,
    atoll: 'Lhaviyani Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'Home to the world\'s largest all-glass underwater restaurant.',
    description: 'Hurawalhi offers an enchanting adults-only experience, famous for its 5.8 Underwater Restaurant.',
    images: ['https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&q=80&w=1200'],
    features: ['5.8 Underwater Restaurant', 'Champagne Pavilion', 'Marine Center', 'Dolphin Cruises'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD, MealPlan.ALL_INCLUSIVE],
    uvp: 'Dine under the sea in the world\'s largest all-glass underwater restaurant.'
  },
  {
    id: 'kuredu-maldives',
    name: 'Kuredu Island Resort & Spa',
    slug: 'kuredu-maldives-vibrant-island',
    type: AccommodationType.RESORT,
    atoll: 'Lhaviyani Atoll',
    priceRange: '$$',
    rating: 4,
    shortDescription: 'Massive island with a wide range of activities and villas.',
    description: 'Kuredu is a popular island choice for active travelers, families, and couples alike, offering one of the largest villa collections.',
    images: ['https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?auto=format&fit=crop&q=80&w=1200'],
    features: ['Golf Club', 'Multiple Pool Areas', 'Sunset Cruises', 'Turtle Sanctuary'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.FULL_BOARD, MealPlan.ALL_INCLUSIVE],
    uvp: 'A massive playground with a dedicated golf course and incredible turtle sightings.'
  }
];

export const OFFERS: Offer[] = [
  {
    id: 'early-bird-2024',
    title: 'Early Bird Summer Escape',
    discount: '30% OFF',
    resortName: 'Soneva Jani',
    expiryDate: '2024-08-31',
    image: 'https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&q=80&w=800',
    category: 'Early Bird'
  },
  {
    id: 'honeymoon-perks',
    title: 'Honeymoon Dreams Bundle',
    discount: 'COMPLIMENTARY DINNER',
    resortName: 'One&Only Reethi Rah',
    expiryDate: '2024-12-31',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&q=80&w=800',
    category: 'Honeymoon'
  },
  {
    id: 'last-minute-luxury',
    title: 'Last Minute Overwater Bliss',
    discount: '40% OFF',
    resortName: 'Adaaran Prestige Vadoo',
    expiryDate: '2024-07-15',
    image: 'https://images.unsplash.com/photo-1573843225233-9fca73af994d?auto=format&fit=crop&q=80&w=800',
    category: 'Last Minute'
  }
];

export const EXPERIENCES: Experience[] = [
  {
    id: 'whale-shark-dive',
    title: 'Whale Shark Quest',
    description: 'Swim alongside the gentle giants of the ocean in the South Ari Atoll marine protected area.',
    image: 'https://images.unsplash.com/photo-1560275619-4662e36fa65c?auto=format&fit=crop&q=80&w=800',
    category: 'Adventure'
  },
  {
    id: 'sandbank-picnic',
    title: 'Private Sandbank Picnic',
    description: 'A castaway experience on a deserted strip of white sand, surrounded only by turquoise waters.',
    image: 'https://images.unsplash.com/photo-1510011564758-29df30730163?auto=format&fit=crop&q=80&w=800',
    category: 'Relaxation'
  },
  {
    id: 'underwater-dining',
    title: 'Gourmet Underwater Dining',
    description: 'Dine 5 meters below the surface with 360-degree views of the coral reef.',
    image: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?auto=format&fit=crop&q=80&w=800',
    category: 'Relaxation'
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'guide-to-transfers',
    title: 'The Ultimate Guide to Maldives Transfers',
    slug: 'maldives-transfer-guide-seaplane-speedboat',
    excerpt: 'Everything you need to know about getting from Velana International Airport to your island paradise.',
    content: 'Navigating the Maldives archipelago requires a mix of seaplanes, speedboats, and domestic flights. Seaplanes offer the most iconic views but only fly during daylight hours...',
    image: 'https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&q=80&w=800',
    date: '2024-05-15',
    author: 'Ahmed Naseem'
  },
  {
    id: 'resort-vs-guesthouse',
    title: 'Resort vs. Guest House: Which is right for you?',
    slug: 'maldives-resort-vs-guesthouse-comparison',
    excerpt: 'Comparing the ultra-luxury private island experience with the authentic charm of local island stays.',
    content: 'While resorts offer total seclusion and luxury, guest houses on islands like Maafushi allow you to experience the local culture and save significantly on your budget...',
    image: 'https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&q=80&w=800',
    date: '2024-06-02',
    author: 'Sarah Jenkins'
  }
];
