
import { Accommodation, AccommodationType, TransferType, MealPlan, Offer, Experience, BlogPost } from './types';

export const RESORTS: Accommodation[] = [
  // --- ULTRA LUXURY & SIGNATURE ---
  {
    id: 'soneva-jani',
    name: 'Soneva Jani',
    slug: 'soneva-jani-luxury-overwater-villas',
    type: AccommodationType.RESORT,
    atoll: 'Noonu Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Iconic overwater villas with private slides into the lagoon.',
    description: 'Soneva Jani is a sanctuary of sustainable luxury. Each villa opens to its own stretch of lagoon and comes with a private pool and a retractable roof to stargaze from the master bedroom.',
    images: ['https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&q=80&w=1200'],
    features: ['Retractable Roof', 'Water Slides', 'Private Pools', 'Outdoor Cinema'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.HALF_BOARD, MealPlan.ALL_INCLUSIVE],
    uvp: 'The only resort in the Maldives with retractable roofs for stargazing and private slides in every villa.',
    isFeatured: true
  },
  {
    id: 'one-only-reethi-rah',
    name: 'One&Only Reethi Rah',
    slug: 'one-and-only-reethi-rah-maldives-luxury',
    type: AccommodationType.RESORT,
    atoll: 'North Male Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Ultra-luxury private island with twelve pristine beaches.',
    description: 'One&Only Reethi Rah offers an unrivaled level of style and sophistication. Surrounded by the crystal clear waters of the Indian Ocean, this superb all-villa resort offers a sanctuary of privacy.',
    images: ['https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&q=80&w=1200'],
    features: ['12 Pristine Beaches', 'Beach Club', 'Private Concierge', 'Overwater Yoga'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Celebrity-favorite private island with twelve distinct beaches and world-class luxury.',
    isFeatured: true
  },
  {
    id: 'waldorf-astoria-ithaafushi',
    name: 'Waldorf Astoria Maldives Ithaafushi',
    slug: 'waldorf-astoria-ithaafushi-luxury-resort',
    type: AccommodationType.RESORT,
    atoll: 'South Male Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Spanning across three private islands with 11 unique dining venues.',
    description: 'Escape to a world of luxury at Waldorf Astoria Maldives Ithaafushi. Offering the ultimate in exclusivity, featuring 11 celebrated dining venues and an Aqua Wellness Center.',
    images: ['https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?auto=format&fit=crop&q=80&w=1200'],
    features: ['11 Dining Venues', 'Private Island Residences', 'Aqua Wellness Center'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Home to the largest private island estate in the Maldives and a unique treehouse dining experience.',
    isFeatured: true
  },
  {
    id: 'ritz-carlton-maldives',
    name: 'The Ritz-Carlton Maldives, Fari Islands',
    slug: 'ritz-carlton-maldives-fari-islands-luxury',
    type: AccommodationType.RESORT,
    atoll: 'North Male Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Architectural masterpiece with a minimalist, circular design.',
    description: 'Set within an integrated island development, the Ritz-Carlton Maldives offers a modern take on Maldivian luxury with its iconic circular villas.',
    images: ['https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&q=80&w=1200'],
    features: ['Circular Villas', 'Fari Marina Access', 'Aris Meeha Butler Service'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Iconic circular architecture and access to the vibrant Fari Marina beach club.',
    isFeatured: true
  },

  // --- BAA ATOLL (UNESCO BIOSPHERE) ---
  {
    id: 'anantara-kihavah',
    name: 'Anantara Kihavah Maldives Villas',
    slug: 'anantara-kihavah-luxury-villas-baa-atoll',
    type: AccommodationType.RESORT,
    atoll: 'Baa Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Home to the world\'s most famous underwater restaurant and overwater observatory.',
    description: 'Located on the Baa Atoll in a UNESCO Biosphere Reserve, Anantara Kihavah offers the ultimate in luxury with its underwater restaurant and overwater observatory.',
    images: ['https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?auto=format&fit=crop&q=80&w=1200'],
    features: ['Underwater Dining', 'SKY Observatory', 'Pool Villas'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'SEA - The world\'s first underwater wine cellar and restaurant.'
  },
  {
    id: 'four-seasons-landaa',
    name: 'Four Seasons Resort Landaa Giraavaru',
    slug: 'four-seasons-landaa-giraavaru-luxury',
    type: AccommodationType.RESORT,
    atoll: 'Baa Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'A remote wilderness of UNESCO-protected coral reefs and world-class service.',
    description: 'Combining innovation and conservation, Landaa Giraavaru is home to the Maldives\' most successful turtle rehabilitation center.',
    images: ['https://images.unsplash.com/photo-1506953064870-15873d93f893?auto=format&fit=crop&q=80&w=1200'],
    features: ['Manta Ray Research', 'Holographic Spa', 'Turtle Rehab'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Home to a holographic spa and the DeepFlight Super Falcon submarine.'
  },
  {
    id: 'amilla-maldives',
    name: 'Amilla Maldives Resort & Residences',
    slug: 'amilla-maldives-resort-residences',
    type: AccommodationType.RESORT,
    atoll: 'Baa Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Spacious white villas and a focus on wellness and ethical dining.',
    description: 'Amilla is known for its "Wellness Your Way" menus and unusually large villas, offering a fresh, modern Maldivian experience.',
    images: ['https://images.unsplash.com/photo-1596436889106-be35e843f974?auto=format&fit=crop&q=80&w=1200'],
    features: ['Ethical Dining', 'Treetop Villas', 'Wellness Your Way'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.ALL_INCLUSIVE],
    uvp: 'The first resort in the Maldives to offer comprehensive Keto, Paleo, and GF menus.'
  },

  // --- SOUTH ARI ATOLL (WHALE SHARKS) ---
  {
    id: 'lux-south-ari',
    name: 'LUX* South Ari Atoll',
    slug: 'lux-south-ari-atoll-whale-shark-diving',
    type: AccommodationType.RESORT,
    atoll: 'South Ari Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'The best place for whale shark sightings year-round with a playful vibe.',
    description: 'Cycle through the tropical pathways of one of the largest islands in the Maldives. Famous for its marine biology center and year-round whale sharks.',
    images: ['https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&q=80&w=1200'],
    features: ['Whale Shark Diving', 'Outdoor Cinema', '8 Restaurants'],
    transfers: [TransferType.SEAPLANE, TransferType.DOMESTIC_FLIGHT],
    mealPlans: [MealPlan.ALL_INCLUSIVE, MealPlan.FULL_BOARD],
    uvp: 'Located in a Marine Protected Area with guaranteed whale shark encounters.'
  },
  {
    id: 'conrad-rangali',
    name: 'Conrad Maldives Rangali Island',
    slug: 'conrad-maldives-rangali-island-underwater-villas',
    type: AccommodationType.RESORT,
    atoll: 'South Ari Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Dual-island concept featuring the world\'s first underwater bedroom.',
    description: 'Rangali Island is spread across two islands connected by a bridge. Home to Ithaa, the world\'s first underwater restaurant.',
    images: ['https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&q=80&w=1200'],
    features: ['The Muraka Villa', 'Ithaa Underwater Restaurant', 'Two-Island Concept'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Home to the first underwater restaurant and the first underwater villa (The Muraka).'
  },

  // --- ADAARAN COLLECTION ---
  {
    id: 'adaaran-vadoo',
    name: 'Adaaran Prestige Vadoo',
    slug: 'adaaran-prestige-vadoo-luxury-water-villas',
    type: AccommodationType.RESORT,
    atoll: 'South Male Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'Award-winning water villas with glass-floor bathrooms.',
    description: 'Located at the gateway to the South Atolls, Adaaran Prestige Vadoo has its own reef teeming with vibrant aquatic flora and fauna.',
    images: ['https://images.unsplash.com/photo-1573843225233-9fca73af994d?auto=format&fit=crop&q=80&w=1200'],
    features: ['Butler Service', 'Glass Floors', 'Plunge Pools'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.ALL_INCLUSIVE],
    uvp: 'The closest all-water-villa resort to Male, perfect for quick luxury escapes.'
  },
  {
    id: 'adaaran-huduran-fushi',
    name: 'Adaaran Select Huduran Fushi',
    slug: 'adaaran-select-huduran-fushi-surf-resort',
    type: AccommodationType.RESORT,
    atoll: 'North Male Atoll',
    priceRange: '$$',
    rating: 4,
    shortDescription: 'Premier surf resort with a legendary left-hand break.',
    description: 'Blessed with thriving vegetation and pristine waters, the "Island of White Gold" is a paradise for surfers and adventure seekers.',
    images: ['https://images.unsplash.com/photo-1502602898657-3e917247a183?auto=format&fit=crop&q=80&w=1200'],
    features: ['Lohis Surf Break', 'Premium All-Inclusive', 'Tennis Courts'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.ALL_INCLUSIVE],
    uvp: 'One of the best surf resorts in the world with exclusive access to the Lohis break.'
  },

  // --- SUN SIYAM GROUP ---
  {
    id: 'siyam-world',
    name: 'Siyam World Maldives',
    slug: 'siyam-world-maldives-all-inclusive-fun',
    type: AccommodationType.RESORT,
    atoll: 'Noonu Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'A massive, fun-filled island with its own water park and horse riding.',
    description: 'Siyam World is one of the largest islands in the Maldives, offering a vast array of activities including horse riding and a massive floating water park.',
    images: ['https://images.unsplash.com/photo-1506929662133-570c13349a7c?auto=format&fit=crop&q=80&w=1200'],
    features: ['Floating Water Park', 'Horse Riding', 'Villas with Slides'],
    transfers: [TransferType.SEAPLANE, TransferType.DOMESTIC_FLIGHT],
    mealPlans: [MealPlan.ALL_INCLUSIVE],
    uvp: 'The largest floating water park in Southeast Asia and the first horse ranch in the Maldives.'
  },
  {
    id: 'sun-siyam-olhuveli',
    name: 'Sun Siyam Olhuveli',
    slug: 'sun-siyam-olhuveli-all-inclusive-resort',
    type: AccommodationType.RESORT,
    atoll: 'South Male Atoll',
    priceRange: '$$',
    rating: 4,
    shortDescription: 'Traditional Maldives meets modern design across three interconnected islands.',
    description: 'Spread across three islands, Sun Siyam Olhuveli offers a massive variety of rooms and water sports activities.',
    images: ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&q=80&w=1200'],
    features: ['3 Swimming Pools', 'Kite Surfing', 'Sandbank Picnics'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.ALL_INCLUSIVE, MealPlan.FULL_BOARD],
    uvp: 'The best value-for-money premium all-inclusive resort in the South Malé Atoll.'
  },

  // --- ADDITIONAL RESORTS ---
  {
    id: 'adaaran-prestige-water-villas',
    name: 'Adaaran Prestige Water Villas',
    slug: 'adaaran-prestige-water-villas',
    type: AccommodationType.RESORT,
    atoll: 'Raa Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Exclusive luxury water villas offering privacy and elegance.',
    description: 'Adaaran Prestige Water Villas offers a premium all-inclusive experience with personalized butler service and stunning glass-bottomed sun decks.',
    images: ['https://images.unsplash.com/photo-1590523278191-995cbcda646b?auto=format&fit=crop&q=80&w=1200'],
    features: ['Personal Butler', 'Glass Bottom Deck', 'Premium All-Inclusive'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.ALL_INCLUSIVE],
    uvp: 'Sophisticated water villas perfect for a romantic getaway.'
  },
  {
    id: 'adaaran-select-meedhupparu',
    name: 'Adaaran Select Meedhupparu',
    slug: 'adaaran-select-meedhupparu',
    type: AccommodationType.RESORT,
    atoll: 'Raa Atoll',
    priceRange: '$$$',
    rating: 4,
    shortDescription: 'A tropical paradise perfect for relaxation and adventure.',
    description: 'Surrounded by a coral reef, Adaaran Select Meedhupparu offers spacious land villas and a variety of water sports.',
    images: ['https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&q=80&w=1200'],
    features: ['Spa', 'Water Sports', 'Kids Club'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.ALL_INCLUSIVE],
    uvp: 'Great value all-inclusive resort with excellent house reef.'
  },
  {
    id: 'alila-kothaifaru-maldives',
    name: 'Alila Kothaifaru Maldives',
    slug: 'alila-kothaifaru-maldives',
    type: AccommodationType.RESORT,
    atoll: 'Raa Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Minimalist luxury surrounded by nature.',
    description: 'Alila Kothaifaru Maldives offers a blend of serenity and discovery in the Raa Atoll, known for its rich marine life.',
    images: ['https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&q=80&w=1200'],
    features: ['Minimalist Design', 'Manta Ray Point', 'Private Pool Villas'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Contemporary minimalist design integrated with nature.'
  },
  {
    id: 'anantara-dhigu-maldives',
    name: 'Anantara Dhigu Maldives Resort',
    slug: 'anantara-dhigu-maldives',
    type: AccommodationType.RESORT,
    atoll: 'South Male Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Family-friendly luxury just a speedboat ride away.',
    description: 'Anantara Dhigu offers spacious villas, a kids club, and access to facilities at neighboring Anantara Veli.',
    images: ['https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&q=80&w=1200'],
    features: ['Family Friendly', 'Surf School', 'Overwater Spa'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Perfect for families with easy access and shared facilities.'
  },
  {
    id: 'anantara-veli-maldives',
    name: 'Anantara Veli Maldives Resort',
    slug: 'anantara-veli-maldives',
    type: AccommodationType.RESORT,
    atoll: 'South Male Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Adults-only sanctuary for romance and relaxation.',
    description: 'Anantara Veli is an adults-only resort featuring overwater bungalows and a tranquil atmosphere.',
    images: ['https://images.unsplash.com/photo-1506953064870-15873d93f893?auto=format&fit=crop&q=80&w=1200'],
    features: ['Adults Only', 'Ayurvedic Spa', 'Open-Air Cinema'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: ' ideally suited for couples seeking a romantic escape.'
  },
  {
    id: 'angsana-velavaru',
    name: 'Angsana Velavaru',
    slug: 'angsana-velavaru',
    type: AccommodationType.RESORT,
    atoll: 'Dhaalu Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'Known as "Turtle Island" with separate in-ocean villas.',
    description: 'Angsana Velavaru features beachfront villas and a separate cluster of standalone In-Ocean Villas.',
    images: ['https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?auto=format&fit=crop&q=80&w=1200'],
    features: ['In-Ocean Villas', 'Marine Lab', 'Kids Club'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.ALL_INCLUSIVE],
    uvp: 'Unique standalone two-story overwater villas.'
  },
  {
    id: 'atmosphere-kanifushi',
    name: 'Atmosphere Kanifushi',
    slug: 'atmosphere-kanifushi',
    type: AccommodationType.RESORT,
    atoll: 'Lhaviyani Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'Premium all-inclusive resort with a 2km long beach.',
    description: 'Atmosphere Kanifushi offers a hassle-free 5-star resort experience with its Platinum Plus all-inclusive plan.',
    images: ['https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&q=80&w=1200'],
    features: ['Platinum Plus Plan', '2km Beach', 'Vegetarian Restaurant'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.ALL_INCLUSIVE],
    uvp: 'One of the longest beaches in the Maldives.'
  },
  {
    id: 'ayada-maldives',
    name: 'Ayada Maldives',
    slug: 'ayada-maldives',
    type: AccommodationType.RESORT,
    atoll: 'Gaafu Dhaalu Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Turkish-themed luxury in the southern atolls.',
    description: 'Ayada Maldives is located on a pristine island with lush tropical greenery and offers a unique Turkish Hammam.',
    images: ['https://images.unsplash.com/photo-1502602898657-3e917247a183?auto=format&fit=crop&q=80&w=1200'],
    features: ['Turkish Hammam', 'Surfing', 'Private Pools'],
    transfers: [TransferType.DOMESTIC_FLIGHT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.ALL_INCLUSIVE],
    uvp: 'Luxury retreat with authentic Turkish hospitality.'
  },
  {
    id: 'bandos-maldives',
    name: 'Bandos Maldives',
    slug: 'bandos-maldives',
    type: AccommodationType.RESORT,
    atoll: 'North Male Atoll',
    priceRange: '$$',
    rating: 4,
    shortDescription: 'A classic Maldivian resort known for its hospitality.',
    description: 'Bandos Maldives is perfect for families and divers, offering a wide range of activities and a convenient location.',
    images: ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&q=80&w=1200'],
    features: ['Dive Centre', 'Convention Centre', 'Family Friendly'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.HALF_BOARD, MealPlan.ALL_INCLUSIVE],
    uvp: 'One of the original and most loved resorts in the Maldives.'
  },
  {
    id: 'baros-maldives',
    name: 'Baros Maldives',
    slug: 'baros-maldives',
    type: AccommodationType.RESORT,
    atoll: 'North Male Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'A legendary boutique resort designed for couples.',
    description: 'Baros Maldives is an intimate coral island known for its lush vegetation and world-class house reef.',
    images: ['https://images.unsplash.com/photo-1506929662133-570c13349a7c?auto=format&fit=crop&q=80&w=1200'],
    features: ['The Lighthouse', 'House Reef', 'Vow Renewals'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'The essence of the Maldives, perfect for romance.'
  },
  {
    id: 'coco-bodu-hithi',
    name: 'Coco Bodu Hithi',
    slug: 'coco-bodu-hithi',
    type: AccommodationType.RESORT,
    atoll: 'North Male Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'Chic and sophisticated island living.',
    description: 'Coco Bodu Hithi reflects the island’s character in every dimension. A chic retreat where you reconnect with yourself.',
    images: ['https://images.unsplash.com/photo-1596436889106-be35e843f974?auto=format&fit=crop&q=80&w=1200'],
    features: ['Large Villas', 'Coco Spa', 'Fine Dining'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.ALL_INCLUSIVE],
    uvp: 'Spacious villas with private pools nestled in nature.'
  },
  {
    id: 'dusit-thani-maldives',
    name: 'Dusit Thani Maldives',
    slug: 'dusit-thani-maldives',
    type: AccommodationType.RESORT,
    atoll: 'Baa Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Thai heritage meets Maldivian luxury in a UNESCO Biosphere.',
    description: 'Dusit Thani Maldives offers Thai hospitality and a spectacular house reef near Hanifaru Bay.',
    images: ['https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&q=80&w=1200'],
    features: ['Devarana Spa', 'Hanifaru Bay', 'Infinity Pool'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.ALL_INCLUSIVE],
    uvp: 'Thai graciousness in the heart of the Maldives.'
  },
  {
    id: 'finolhu-maldives',
    name: 'Finolhu Baa Atoll',
    slug: 'finolhu-maldives',
    type: AccommodationType.RESORT,
    atoll: 'Baa Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'A playful retro-chic resort with a 2km sandbank.',
    description: 'Finolhu brings a retro-inspired fun vibe to the Maldives, featuring unique bubble tents and a long sandbank.',
    images: ['https://images.unsplash.com/photo-1510011564758-29df30730163?auto=format&fit=crop&q=80&w=1200'],
    features: ['Beach Bubble', 'Longest Sandbank', 'Retro Vibe'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.ALL_INCLUSIVE],
    uvp: 'Sleep under the stars in the unique Beach Bubble.'
  },
  {
    id: 'gili-lankanfushi',
    name: 'Gili Lankanfushi',
    slug: 'gili-lankanfushi',
    type: AccommodationType.RESORT,
    atoll: 'North Male Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Eco-luxury sanctuary with massive overwater villas.',
    description: 'Gili Lankanfushi is an intimate coral island in a sparkling lagoon, with jetties threading across the water out to spacious villas.',
    images: ['https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?auto=format&fit=crop&q=80&w=1200'],
    features: ['Private Reserve', 'Mr. Friday Butler', 'Eco-Friendly'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Home to the largest overwater villa in the world.'
  },
  {
    id: 'hard-rock-hotel-maldives',
    name: 'Hard Rock Hotel Maldives',
    slug: 'hard-rock-hotel-maldives',
    type: AccommodationType.RESORT,
    atoll: 'South Male Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'Upbeat vibe and musical memorabilia at The Marina.',
    description: 'Located at CROSSROADS Maldives, Hard Rock Hotel offers a rocking stay with direct access to The Marina’s dining and shopping.',
    images: ['https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&q=80&w=1200'],
    features: ['Hard Rock Cafe', 'Music Amenities', 'Kids Club'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.ALL_INCLUSIVE],
    uvp: 'The only Hard Rock experience in the Maldives.'
  },
  {
    id: 'hurawalhi-island-resort',
    name: 'Hurawalhi Island Resort',
    slug: 'hurawalhi-island-resort',
    type: AccommodationType.RESORT,
    atoll: 'Lhaviyani Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Adults-only paradise with the 5.8 Undersea Restaurant.',
    description: 'Hurawalhi is a perfect match of serenity and excitement, comfort and adventure. Home to the world\'s largest all-glass undersea restaurant.',
    images: ['https://images.unsplash.com/photo-1573843225233-9fca73af994d?auto=format&fit=crop&q=80&w=1200'],
    features: ['5.8 Undersea Restaurant', 'Adults Only', 'Marine Biology Center'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.ALL_INCLUSIVE],
    uvp: 'Dine in the world\'s largest all-glass undersea restaurant.'
  },
  {
    id: 'joali-maldives',
    name: 'JOALI Maldives',
    slug: 'joali-maldives',
    type: AccommodationType.RESORT,
    atoll: 'Raa Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Immersive art resort with ultra-luxury villas.',
    description: 'JOALI is an art-immersive island retreat, designed to inspire and delight with its collection of interactive art pieces.',
    images: ['https://images.unsplash.com/photo-1506929662133-570c13349a7c?auto=format&fit=crop&q=80&w=1200'],
    features: ['Art Studio', 'Muramas Kids Club', 'Espa Spa'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'The first art-immersive resort in the Maldives.'
  },
  {
    id: 'kuramathi-maldives',
    name: 'Kuramathi Maldives',
    slug: 'kuramathi-maldives',
    type: AccommodationType.RESORT,
    atoll: 'North Ari Atoll',
    priceRange: '$$$',
    rating: 4,
    shortDescription: 'A large island with something for everyone and a mile-long sandbank.',
    description: 'Kuramathi is one of the larger islands, offering a wide array of villas, dining options, and nature trails.',
    images: ['https://images.unsplash.com/photo-1596436889106-be35e843f974?auto=format&fit=crop&q=80&w=1200'],
    features: ['Mile-long Sandbank', 'Eco Centre', '12 Restaurants'],
    transfers: [TransferType.SPEEDBOAT, TransferType.SEAPLANE],
    mealPlans: [MealPlan.FULL_BOARD, MealPlan.ALL_INCLUSIVE],
    uvp: 'An island of choice with extensive facilities and natural beauty.'
  },
  {
    id: 'lux-north-male',
    name: 'Jumeirah Olhahali Island',
    slug: 'jumeirah-olhahali',
    type: AccommodationType.RESORT,
    atoll: 'North Male Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Contemporary all-villa resort with rooftop terraces.',
    description: 'Jumeirah Olhahali Island (formerly LUX* North Male) features penthouse-style villas with private rooftop decks.',
    images: ['https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&q=80&w=1200'],
    features: ['Rooftop Terraces', 'Contemporary Design', 'Private Pools'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.ALL_INCLUSIVE],
    uvp: 'Forward-thinking design with private rooftop lounges.'
  },
  {
    id: 'milaidhoo-maldives',
    name: 'Milaidhoo Maldives',
    slug: 'milaidhoo-maldives',
    type: AccommodationType.RESORT,
    atoll: 'Baa Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Butique luxury focusing on the "Reinvented Luxury".',
    description: 'Milaidhoo is a small, stylish island that offers a return to classic, relaxed Maldivian style with modern comforts.',
    images: ['https://images.unsplash.com/photo-1510011564758-29df30730163?auto=format&fit=crop&q=80&w=1200'],
    features: ['Ba\'theli Restaurant', 'Hanifaru Bay', 'Private Residenes'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'A member of Small Luxury Hotels of the World.'
  },
  {
    id: 'six-senses-laamu',
    name: 'Six Senses Laamu',
    slug: 'six-senses-laamu',
    type: AccommodationType.RESORT,
    atoll: 'Laamu Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'The only resort in the Laamu Atoll, offering sustainable luxury.',
    description: 'Six Senses Laamu is a palm-fringed paradise where sustainability and luxury meet. Famous for its surfing and marine conservation.',
    images: ['https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&q=80&w=1200'],
    features: ['Surfing (Yin Yang)', 'Sustainability', 'Ice Cream Parlor'],
    transfers: [TransferType.DOMESTIC_FLIGHT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Uncharted luxury in the remote Laamu Atoll.'
  },
  {
    id: 'st-regis-vommuli',
    name: 'The St. Regis Maldives Vommuli Resort',
    slug: 'st-regis-vommuli',
    type: AccommodationType.RESORT,
    atoll: 'Dhaalu Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Avant-garde architecture and legendary St. Regis butler service.',
    description: 'The St. Regis Maldives Vommuli Resort offers a degree of isolation and luxury that is unparalleled, with the Iridium Spa and Whale Bar.',
    images: ['https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?auto=format&fit=crop&q=80&w=1200'],
    features: ['Iridium Spa', 'Butler Service', 'Whale Bar'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST],
    uvp: 'Home to the Blue Hole pool and John Jacob Astor Estate.'
  },
  {
    id: 'vakkaru-maldives',
    name: 'Vakkaru Maldives',
    slug: 'vakkaru-maldives',
    type: AccommodationType.RESORT,
    atoll: 'Baa Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Timeless sanctuary in the UNESCO Biosphere Reserve.',
    description: 'Vakkaru Maldives is a lush tropical island with 2,300 coconut trees and a house reef rich in marine life.',
    images: ['https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&q=80&w=1200'],
    features: ['Coconut Plantation', 'Overwater Spa', 'Tennis Courts'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'A secluded reef island blessed with timeless ocean views.'
  },
  {
    id: 'velassaru-maldives',
    name: 'Velassaru Maldives',
    slug: 'velassaru-maldives',
    type: AccommodationType.RESORT,
    atoll: 'South Male Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'Youthful and chic resort with a stunning turquoise lagoon.',
    description: 'Velassaru offers luxurious beachfront and overwater accommodation with unobstructed ocean views.',
    images: ['https://images.unsplash.com/photo-1506953064870-15873d93f893?auto=format&fit=crop&q=80&w=1200'],
    features: ['Infinity Pool', 'Chill Bar', 'Photography'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.FULL_BOARD],
    uvp: 'Contemporary luxury with a distinctively playful vibe.'
  },
  {
    id: 'w-maldives',
    name: 'W Maldives',
    slug: 'w-maldives',
    type: AccommodationType.RESORT,
    atoll: 'North Ari Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Bold and unscripted luxury with a vibrant house reef.',
    description: 'W Maldives is a luxury playground in a wonderland of white sand beaches, turquoise lagoons, and breathtaking reefs.',
    images: ['https://images.unsplash.com/photo-1573843225233-9fca73af994d?auto=format&fit=crop&q=80&w=1200'],
    features: ['Whatever/Whenever', 'House Reef', 'Underground Club'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.ALL_INCLUSIVE],
    uvp: 'Fuel your lust for life at this heart-pumping resort.'
  },

  // --- BATCH 2 RESORTS ---
  {
    id: 'centara-ras-fushi',
    name: 'Centara Ras Fushi Resort & Spa',
    slug: 'centara-ras-fushi',
    type: AccommodationType.RESORT,
    atoll: 'North Male Atoll',
    priceRange: '$$$',
    rating: 4,
    shortDescription: 'Adults-only retreat ideal for couples and honeymooners.',
    description: 'Centara Ras Fushi offers a relaxing atmosphere with light and airy villas, just 20 minutes from Velana International Airport.',
    images: ['https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&q=80&w=1200'],
    features: ['Adults Only', 'Thai Spa', 'E-Zone'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.ALL_INCLUSIVE, MealPlan.HALF_BOARD],
    uvp: 'Quick speedboat transfer and adults-only tranquility.'
  },
  {
    id: 'cinnamon-dhonveli',
    name: 'Cinnamon Dhonveli Maldives',
    slug: 'cinnamon-dhonveli',
    type: AccommodationType.RESORT,
    atoll: 'North Male Atoll',
    priceRange: '$$$',
    rating: 4,
    shortDescription: 'A surfer’s paradise with the famous Pasta Point break.',
    description: 'Cinnamon Dhonveli is a high-energy resort popular with surfers, offering exclusive access to Pasta Point.',
    images: ['https://images.unsplash.com/photo-1502602898657-3e917247a183?auto=format&fit=crop&q=80&w=1200'],
    features: ['Pasta Point Surf', 'Overwater Suites', 'Family Friendly'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.ALL_INCLUSIVE],
    uvp: 'Exclusive access to one of the most consistent surf breaks.'
  },
  {
    id: 'constance-moofushi',
    name: 'Constance Moofushi Maldives',
    slug: 'constance-moofushi',
    type: AccommodationType.RESORT,
    atoll: 'South Ari Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Chic barefoot luxury with a premium all-inclusive plan.',
    description: 'Constance Moofushi is situated on a migration route for manta rays and offers a perfect combination of luxury and simplicity.',
    images: ['https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?auto=format&fit=crop&q=80&w=1200'],
    features: ['Manta Point', 'Bio-Marine Spa', 'Wine Cellar'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.ALL_INCLUSIVE],
    uvp: 'One of the best diving and snorkeling spots in the world.'
  },
  {
    id: 'coco-palm-dhuni-kolhu',
    name: 'Coco Palm Dhuni Kolhu',
    slug: 'coco-palm-dhuni-kolhu',
    type: AccommodationType.RESORT,
    atoll: 'Baa Atoll',
    priceRange: '$$$',
    rating: 4,
    shortDescription: 'Eco-oriented resort in the UNESCO Biosphere Reserve.',
    description: 'Coco Palm Dhuni Kolhu is dedicated to preserving the environment and offers a rustic, back-to-nature experience.',
    images: ['https://images.unsplash.com/photo-1510011564758-29df30730163?auto=format&fit=crop&q=80&w=1200'],
    features: ['Turtle Rescue Centre', 'Eco-Friendly', 'Rustic Villas'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.ALL_INCLUSIVE],
    uvp: 'Home to the Olive Ridley Project turtle rescue centre.'
  },
  {
    id: 'dhigali-maldives',
    name: 'Dhigali Maldives',
    slug: 'dhigali-maldives',
    type: AccommodationType.RESORT,
    atoll: 'Raa Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'Innovative premium all-inclusive resort with modern design.',
    description: 'Dhigali Maldives features a slender coral cay with a house reef and a loop of island life including a jungle walk.',
    images: ['https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&q=80&w=1200'],
    features: ['Premium All-Inclusive', 'Jungle Walk', 'Haali Bar'],
    transfers: [TransferType.SEAPLANE, TransferType.DOMESTIC_FLIGHT],
    mealPlans: [MealPlan.ALL_INCLUSIVE],
    uvp: 'Excellent value premium all-inclusive with diverse dining.'
  },
  {
    id: 'emerald-maldives',
    name: 'Emerald Maldives Resort & Spa',
    slug: 'emerald-maldives',
    type: AccommodationType.RESORT,
    atoll: 'Raa Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Deluxe all-inclusive resort member of Leading Hotels of the World.',
    description: 'Emerald Maldives blends harmony with the environment and tropical luxury, featuring a vast lagoon and stylish villas.',
    images: ['https://images.unsplash.com/photo-1573843225233-9fca73af994d?auto=format&fit=crop&q=80&w=1200'],
    features: ['Deluxe All-Inclusive', 'Kids Club', 'South American Steakhouse'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.ALL_INCLUSIVE],
    uvp: 'Outstanding deluxe all-inclusive catering to families and couples.'
  },
  {
    id: 'grand-park-kodhipparu',
    name: 'Grand Park Kodhipparu',
    slug: 'grand-park-kodhipparu',
    type: AccommodationType.RESORT,
    atoll: 'North Male Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'One-island-one-resort destination just 20 minutes from Male.',
    description: 'Grand Park Kodhipparu offers sophisticated villas and an award-winning spa, perfect for a quick luxury escape.',
    images: ['https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&q=80&w=1200'],
    features: ['Overwater Spa', 'Infinity Pool', 'Dive Centre'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.ALL_INCLUSIVE],
    uvp: 'Convenient luxury with stunning overwater villas.'
  },
  {
    id: 'heritance-aarah',
    name: 'Heritance Aarah',
    slug: 'heritance-aarah',
    type: AccommodationType.RESORT,
    atoll: 'Raa Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Premium all-inclusive resort with a dedicated Medi-Spa.',
    description: 'Heritance Aarah offers an immersive Maldivian experience with a focus on heritage and wellness.',
    images: ['https://images.unsplash.com/photo-1596436889106-be35e843f974?auto=format&fit=crop&q=80&w=1200'],
    features: ['Medi-Spa', 'Ocean Suites', 'Cultural Village'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.ALL_INCLUSIVE],
    uvp: 'First Medi-Spa in the Maldives and rich cultural experiences.'
  },
  {
    id: 'huvafen-fushi',
    name: 'Huvafen Fushi',
    slug: 'huvafen-fushi',
    type: AccommodationType.RESORT,
    atoll: 'North Male Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Iconic adults-only resort with the world\'s first underwater spa.',
    description: 'Huvafen Fushi is a dreamscape of hidden pleasures, featuring private pools in every villa and a legendary underwater spa.',
    images: ['https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?auto=format&fit=crop&q=80&w=1200'],
    features: ['Underwater Spa', 'Underground Wine Cellar', 'Adults Only'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'The pioneer of underwater spa treatments.'
  },
  {
    id: 'intercontinental-maldives',
    name: 'InterContinental Maldives Maamunagau',
    slug: 'intercontinental-maldives',
    type: AccommodationType.RESORT,
    atoll: 'Raa Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Club InterContinental benefits for all guests.',
    description: 'InterContinental Maldives Maamunagau Resort offers exclusive Club InterContinental benefits to all guests, including afternoon tea and evening aperitifs.',
    images: ['https://images.unsplash.com/photo-1506929662133-570c13349a7c?auto=format&fit=crop&q=80&w=1200'],
    features: ['All-Club Benefits', 'Lighthouse View', 'Manta Sanctuary'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'First and only all-Club InterContinental resort.'
  },
  {
    id: 'jw-marriott-maldives',
    name: 'JW Marriott Maldives Resort & Spa',
    slug: 'jw-marriott-maldives',
    type: AccommodationType.RESORT,
    atoll: 'Shaviyani Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Luxury family resort with a massive kids club.',
    description: 'JW Marriott Maldives Resort & Spa offers 60 spacious villas and one of the largest kids clubs in the Maldives, FAMiLY by JW.',
    images: ['https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&q=80&w=1200'],
    features: ['FAMiLY by JW', 'Overwater Pool', 'Treetop Dining'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.ALL_INCLUSIVE],
    uvp: 'Exceptional facilities for multi-generational travel.'
  },
  {
    id: 'kandima-maldives',
    name: 'Kandima Maldives',
    slug: 'kandima-maldives',
    type: AccommodationType.RESORT,
    atoll: 'Dhaalu Atoll',
    priceRange: '$$$',
    rating: 4,
    shortDescription: 'A game-changing lifestyle resort for the active and fun-loving.',
    description: 'Kandima is more than just a holiday, it’s a lifestyle. With a 3km long beach and the longest outdoor pool in the Maldives.',
    images: ['https://images.unsplash.com/photo-1510011564758-29df30730163?auto=format&fit=crop&q=80&w=1200'],
    features: ['Longest Pool', 'Art Studio', 'Kula Run'],
    transfers: [TransferType.SEAPLANE, TransferType.DOMESTIC_FLIGHT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.ALL_INCLUSIVE],
    uvp: 'Affordable luxury with a seriously stylish vibe.'
  },
  {
    id: 'kurumba-maldives',
    name: 'Kurumba Maldives',
    slug: 'kurumba-maldives',
    type: AccommodationType.RESORT,
    atoll: 'North Male Atoll',
    priceRange: '$$',
    rating: 5,
    shortDescription: 'The very first resort in the Maldives, rich in history.',
    description: 'Kurumba Maldives offers a convenient location near the airport, a vibrant social scene, and a wide range of accommodation.',
    images: ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&q=80&w=1200'],
    features: ['Proximity to Airport', '7 Restaurants', 'Vibrant Nightlife'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.ALL_INCLUSIVE],
    uvp: 'The pioneer of Maldives tourism.'
  },
  {
    id: 'lily-beach-resort',
    name: 'Lily Beach Resort & Spa',
    slug: 'lily-beach-resort',
    type: AccommodationType.RESORT,
    atoll: 'South Ari Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Pioneer of the Platinum Plan premium all-inclusive.',
    description: 'Lily Beach Resort & Spa is a leading family-friendly resort known for its generous Platinum Plan and excellent house reef.',
    images: ['https://images.unsplash.com/photo-1573843225233-9fca73af994d?auto=format&fit=crop&q=80&w=1200'],
    features: ['Platinum Plan', 'Family Friendly', 'House Reef'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.ALL_INCLUSIVE],
    uvp: 'Worry-free luxury with the Platinum Plan.'
  },
  {
    id: 'meeru-maldives',
    name: 'Meeru Maldives Resort Island',
    slug: 'meeru-maldives',
    type: AccommodationType.RESORT,
    atoll: 'North Male Atoll',
    priceRange: '$$',
    rating: 4,
    shortDescription: 'One of the largest islands offering a "simply Maldives" feel.',
    description: 'Meeru Island Resort & Spa is a large, classic resort with separate adults-only and family areas.',
    images: ['https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&q=80&w=1200'],
    features: ['Two Spas', 'Golf Course', 'Adults Only Area'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.FULL_BOARD, MealPlan.ALL_INCLUSIVE],
    uvp: 'Classic Maldivian hospitality on a large, feature-rich island.'
  },
  {
    id: 'niyama-private-islands',
    name: 'Niyama Private Islands',
    slug: 'niyama-private-islands',
    type: AccommodationType.RESORT,
    atoll: 'Dhaalu Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Twin islands "Play" and "Chill" offering the best of both worlds.',
    description: 'Niyama Private Islands offers a unique concept of two islands, one for family fun and one for couples’ relaxation, plus an underwater club.',
    images: ['https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?auto=format&fit=crop&q=80&w=1200'],
    features: ['Subsix Underwater Club', 'Surf Point', 'Kid\'s Club'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Luxury surfing and the world\'s first underwater nightclub.'
  },
  {
    id: 'oblu-select-sangeli',
    name: 'OBLU SELECT Sangeli',
    slug: 'oblu-select-sangeli',
    type: AccommodationType.RESORT,
    atoll: 'North Male Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'Chic beach resort with a separate "One Banyan" adults-only island.',
    description: 'OBLU SELECT Sangeli offers a premium all-inclusive Serenity Plan and features a unique mini-island just for adults.',
    images: ['https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&q=80&w=1200'],
    features: ['Serenity Plan', 'One Banyan Island', 'Water Slide'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.ALL_INCLUSIVE],
    uvp: 'Exclusive adults-only island connected by a wooden jetty.'
  },
  {
    id: 'ozen-life-maadhoo',
    name: 'OZEN LIFE MAADHOO',
    slug: 'ozen-life-maadhoo',
    type: AccommodationType.RESORT,
    atoll: 'South Male Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Luxury all-inclusive with Indulgence™ Plan and underwater dining.',
    description: 'OZEN LIFE MAADHOO offers an encompassing lifestyle luxury plan including underwater dining at M6m.',
    images: ['https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&q=80&w=1200'],
    features: ['M6m Underwater Restaurant', 'Indulgence Plan', 'Champagne Breakfast'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.ALL_INCLUSIVE],
    uvp: 'No-shocks luxury all-inclusive experience.'
  },
  {
    id: 'park-hyatt-maldives',
    name: 'Park Hyatt Maldives Hadahaa',
    slug: 'park-hyatt-maldives',
    type: AccommodationType.RESORT,
    atoll: 'Gaafu Alifu Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Architecture and nature in perfect harmony near the equator.',
    description: 'Park Hyatt Maldives Hadahaa features minimalist architecture that preserves the natural environment and one of the best house reefs.',
    images: ['https://images.unsplash.com/photo-1506929662133-570c13349a7c?auto=format&fit=crop&q=80&w=1200'],
    features: ['360 House Reef', 'Equator Trip', 'Vidhun Spa'],
    transfers: [TransferType.DOMESTIC_FLIGHT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Remote luxury with a focus on marine conservation.'
  },
  {
    id: 'sheraton-maldives',
    name: 'Sheraton Maldives Full Moon Resort & Spa',
    slug: 'sheraton-maldives',
    type: AccommodationType.RESORT,
    atoll: 'North Male Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'A gathering place for families and friends near Male.',
    description: 'Sheraton Maldives Full Moon Resort & Spa is a tropical paradise with a wide range of accommodation and extensive facilities.',
    images: ['https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&q=80&w=1200'],
    features: ['Shine Spa', 'Lagoon View', 'Orchid Garden'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.ALL_INCLUSIVE],
    uvp: 'Classic brand reliability with extensive renovation.'
  },
  {
    id: 'sun-siyam-iru-fushi',
    name: 'Sun Siyam Iru Fushi',
    slug: 'sun-siyam-iru-fushi',
    type: AccommodationType.RESORT,
    atoll: 'Noonu Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'Massive island playground with an award-winning spa.',
    description: 'Sun Siyam Iru Fushi is a spacious resort offering extensive facilities for families and one of the largest spas in the Maldives.',
    images: ['https://images.unsplash.com/photo-1596436889106-be35e843f974?auto=format&fit=crop&q=80&w=1200'],
    features: ['The Spa by Thalgo', 'Family Friendly', '14 Bars & Restaurants'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.ALL_INCLUSIVE],
    uvp: 'Something for everyone with huge variety.'
  },
  {
    id: 'taj-exotica',
    name: 'Taj Exotica Resort & Spa',
    slug: 'taj-exotica',
    type: AccommodationType.RESORT,
    atoll: 'South Male Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Award-winning resort on one of the largest lagoons.',
    description: 'Taj Exotica Resort & Spa is renowned for its Jiva Grande Spa and exquisite cuisine, set in a massive turquoise lagoon.',
    images: ['https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?auto=format&fit=crop&q=80&w=1200'],
    features: ['Jiva Grande Spa', 'Deep Lagoon', 'Fine Dining'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Romantic luxury with impeccable Indian hospitality.'
  },
  {
    id: 'the-nautilus-maldives',
    name: 'The Nautilus Maldives',
    slug: 'the-nautilus-maldives',
    type: AccommodationType.RESORT,
    atoll: 'Baa Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Ultra-luxe bohemian hideaway with no set schedules.',
    description: 'The Nautilus Maldives is a highly exclusive private island resort where time stands still and guests have total freedom.',
    images: ['https://images.unsplash.com/photo-1510011564758-29df30730163?auto=format&fit=crop&q=80&w=1200'],
    features: ['Unscripted Dining', 'Private Butler', 'Vintage Champagne'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST],
    uvp: 'A home without rules, customized to your every whim.'
  },
  {
    id: 'the-standard-huruvalhi',
    name: 'The Standard, Huruvalhi Maldives',
    slug: 'the-standard-huruvalhi',
    type: AccommodationType.RESORT,
    atoll: 'Raa Atoll',
    priceRange: '$$$',
    rating: 5,
    shortDescription: 'Social and vibrant resort with a glass-bottom nightclub.',
    description: 'The Standard, Huruvalhi Maldives brings a fresh, cool vibe to the Maldives with social activities and unique design.',
    images: ['https://images.unsplash.com/photo-1506929662133-570c13349a7c?auto=format&fit=crop&q=80&w=1200'],
    features: ['Glass Bottom Nightclub', 'Social Vibe', 'Activity Wall'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.ALL_INCLUSIVE],
    uvp: 'Non-stop fun and social connection.'
  },
  {
    id: 'westin-maldives',
    name: 'The Westin Maldives Miriandhoo Resort',
    slug: 'westin-maldives',
    type: AccommodationType.RESORT,
    atoll: 'Baa Atoll',
    priceRange: '$$$$',
    rating: 5,
    shortDescription: 'Wellness-focused resort designed by award-winning architects.',
    description: 'The Westin Maldives Miriandhoo Resort offers a rejuvenating stay with its Heavenly Beds and focus on well-being.',
    images: ['https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&q=80&w=1200'],
    features: ['Heavenly Spa', 'Wellness Focus', 'Hanifaru Bay'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Sleep Well, Eat Well, Move Well philosophy.'
  },
  {
    id: 'veligandu-maldives',
    name: 'Veligandu Maldives Resort Island',
    slug: 'veligandu-maldives',
    type: AccommodationType.RESORT,
    atoll: 'North Ari Atoll',
    priceRange: '$$$',
    rating: 4,
    shortDescription: 'Charming island with a beautiful sandbank and house reef.',
    description: 'Veligandu Maldives Resort Island is one of the oldest and most popular resorts, known for its friendly service and sandbank.',
    images: ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&q=80&w=1200'],
    features: ['Sandbank', 'Adults Only Area', 'House Reef'],
    transfers: [TransferType.SEAPLANE],
    mealPlans: [MealPlan.FULL_BOARD, MealPlan.ALL_INCLUSIVE],
    uvp: 'Authentic Maldivian charm with a spectacular sandbank.'
  },

  // --- GUEST HOUSES (LOCAL ISLANDS) ---
  {
    id: 'kaani-grand-maafushi',
    name: 'Kaani Grand Seaview',
    slug: 'kaani-grand-seaview-maafushi-guest-house',
    type: AccommodationType.GUEST_HOUSE,
    atoll: 'South Male Atoll',
    priceRange: '$',
    rating: 4,
    shortDescription: 'Premier beachside guest house in the heart of Maafushi local island.',
    description: 'Experience the real Maldives. Kaani Grand Seaview offers premium accommodation directly facing the bikini beach of Maafushi.',
    images: ['https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&q=80&w=1200'],
    features: ['Bikini Beach Access', 'Rooftop Dining', 'Daily Excursions'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'The most popular high-end stay on Maafushi local island with resort-style amenities.'
  },
  {
    id: 'season-paradise-thulusdhoo',
    name: 'Season Paradise',
    slug: 'season-paradise-thulusdhoo-surf-hotel',
    type: AccommodationType.GUEST_HOUSE,
    atoll: 'North Male Atoll',
    priceRange: '$',
    rating: 4,
    shortDescription: 'Award-winning surf hotel on the vibrant local island of Thulusdhoo.',
    description: 'Season Paradise is a 48-room boutique hotel offering an rooftop infinity pool and direct access to Cokes and Chickens surf breaks.',
    images: ['https://images.unsplash.com/photo-1502602898657-3e917247a183?auto=format&fit=crop&q=80&w=1200'],
    features: ['Rooftop Infinity Pool', 'Surf Breaks Access', 'Local Island Tours'],
    transfers: [TransferType.SPEEDBOAT],
    mealPlans: [MealPlan.BED_BREAKFAST, MealPlan.HALF_BOARD],
    uvp: 'Voted the leading guest house in the Maldives, offering a rooftop pool with surf break views.'
  },
  {
    id: 'barefoot-eco-hotel',
    name: 'The Barefoot Eco Hotel',
    slug: 'barefoot-eco-hotel-hanimaadhoo-maldives',
    type: AccommodationType.GUEST_HOUSE,
    atoll: 'Haa Alifu Atoll',
    priceRange: '$',
    rating: 4,
    shortDescription: 'Unique ecological project on a local island with a focus on conservation.',
    description: 'Authentic Maldivian experiences on a local island with a focus on conservation and community. Located in the northernmost atoll.',
    images: ['https://images.unsplash.com/photo-1510011564758-29df30730163?auto=format&fit=crop&q=80&w=1200'],
    features: ['Marine Biology Center', 'Private Bikini Beach', 'Yoga Retreats'],
    transfers: [TransferType.DOMESTIC_FLIGHT],
    mealPlans: [MealPlan.HALF_BOARD, MealPlan.BED_BREAKFAST],
    uvp: 'The most sustainable guest house in the Maldives with its own private beach and forest area.'
  }
];

export const OFFERS: Offer[] = [
  {
    id: 'early-bird-2024',
    title: 'Early Bird Summer Escape',
    discount: '30% OFF',
    resortName: 'Soneva Jani',
    expiryDate: '2024-08-31',
    image: 'https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&q=80&w=800',
    category: 'Early Bird'
  },
  {
    id: 'honeymoon-perks',
    title: 'Honeymoon Dreams Bundle',
    discount: 'COMPLIMENTARY DINNER',
    resortName: 'One&Only Reethi Rah',
    expiryDate: '2024-12-31',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&q=80&w=800',
    category: 'Honeymoon'
  },
  {
    id: 'last-minute-luxury',
    title: 'Last Minute Overwater Bliss',
    discount: '40% OFF',
    resortName: 'Adaaran Prestige Vadoo',
    expiryDate: '2024-07-15',
    image: 'https://images.unsplash.com/photo-1573843225233-9fca73af994d?auto=format&fit=crop&q=80&w=800',
    category: 'Last Minute'
  }
];

export const EXPERIENCES: Experience[] = [
  {
    id: 'whale-shark-dive',
    title: 'Whale Shark Quest',
    description: 'Swim alongside the gentle giants of the ocean in the South Ari Atoll marine protected area.',
    image: 'https://images.unsplash.com/photo-1560275619-4662e36fa65c?auto=format&fit=crop&q=80&w=800',
    category: 'Adventure'
  },
  {
    id: 'sandbank-picnic',
    title: 'Private Sandbank Picnic',
    description: 'A castaway experience on a deserted strip of white sand, surrounded only by turquoise waters.',
    image: 'https://images.unsplash.com/photo-1510011564758-29df30730163?auto=format&fit=crop&q=80&w=800',
    category: 'Relaxation'
  },
  {
    id: 'underwater-dining',
    title: 'Gourmet Underwater Dining',
    description: 'Dine 5 meters below the surface with 360-degree views of the coral reef.',
    image: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?auto=format&fit=crop&q=80&w=800',
    category: 'Relaxation'
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'guide-to-transfers',
    title: 'The Ultimate Guide to Maldives Transfers',
    slug: 'maldives-transfer-guide-seaplane-speedboat',
    excerpt: 'Everything you need to know about getting from Velana International Airport to your island paradise.',
    content: 'Navigating the Maldives archipelago requires a mix of seaplanes, speedboats, and domestic flights. Seaplanes offer the most iconic views but only fly during daylight hours...',
    image: 'https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&q=80&w=800',
    date: '2024-05-15',
    author: 'Ahmed Naseem'
  },
  {
    id: 'resort-vs-guesthouse',
    title: 'Resort vs. Guest House: Which is right for you?',
    slug: 'maldives-resort-vs-guesthouse-comparison',
    excerpt: 'Comparing the ultra-luxury private island experience with the authentic charm of local island stays.',
    content: 'While resorts offer total seclusion and luxury, guest houses on islands like Maafushi allow you to experience the local culture and save significantly on your budget...',
    image: 'https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&q=80&w=800',
    date: '2024-06-02',
    author: 'Sarah Jenkins'
  }
];
